name: Update Workflow

on:
  schedule:
    - cron: '0 10 * * 5'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v2

      - name: Clone stable-diffusion-webui-extensions
        run: |
          mkdir -p /tmp/sdwe
          git clone https://github.com/AUTOMATIC1111/stable-diffusion-webui-extensions /tmp/sdwe
          rm -rf /tmp/sdwe/README.md /tmp/sdwe/.github/ /tmp/sdwe/.git/

      - name: Update JSON files
        run: |
          find /tmp/sdwe -name '*.json' -exec sed -i 's|https://github.com|https://ghp.ci/https://github.com|g' {} +

      - name: Sync files
        run: |
          rsync -av --ignore-existing /tmp/sdwe/ ./
          rsync -av --update /tmp/sdwe/ ./

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update" || echo "No changes to commit"
          git push
